### ISSUE TITLE
RTD Failing

### ISSUE THREAD

**Issue by david4096** [ga4gh/schemas#819]
May be a conda or OpenSSL issue.

Created a conda issue [here](
https://github.com/conda/conda/issues/4693).

https://readthedocs.org/projects/ga4gh-schemas/builds/5051360/
```
`$ /usr/local/miniconda/bin/conda-env create --name latest --file /home/docs/checkouts/readthedocs.org/user_builds/ga4gh-schemas/checkouts/latest/doc/source/environment.yml`




    Traceback (most recent call last):
      File "/usr/local/miniconda/lib/python2.7/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/usr/local/miniconda/lib/python2.7/site-packages/conda_env/cli/main_create.py", line 111, in execute
        installer.install(prefix, pkg_specs, args, env)
      File "/usr/local/miniconda/lib/python2.7/site-packages/conda_env/installers/conda.py", line 38, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Could not open u'/usr/local/miniconda/pkgs/sqlite-3.13.0-0.tar.bz2.part' for writing ([Errno 13] Permission denied: u'/usr/local/miniconda/pkgs/sqlite-3.13.0-0.tar.bz2.part').

 MB/s
openssl-1.0.2h  75% |#######################        | ETA:  0:00:00  24.79 MB/s
openssl-1.0.2h  76% |#######################        | ETA:  0:00:00  25.00 MB/s
openssl-1.0.2h  78% |########################       | ETA:  0:00:00  25.03 MB/s
openssl-1.0.2h  79% |########################       | ETA:  0:00:00  25.10 MB/s
openssl-1.0.2h  81% |#########################      | ETA:  0:00:00  25.36 MB/s
openssl-1.0.2h  82% |#########################      | ETA:  0:00:00  25.44 MB/s
openssl-1.0.2h  84% |##########################     | ETA:  0:00:00  25.55 MB/s
openssl-1.0.2h  85% |##########################     | ETA:  0:00:00  25.68 MB/s
openssl-1.0.2h  87% |###########################    | ETA:  0:00:00  25.86 MB/s
openssl-1.0.2h  88% |###########################    | ETA:  0:00:00  26.01 MB/s
openssl-1.0.2h  90% |###########################    | ETA:  0:00:00  26.16 MB/s
openssl-1.0.2h  91% |############################   | ETA:  0:00:00  26.20 MB/s
openssl-1.0.2h  93% |############################   | ETA:  0:00:00  26.34 MB/s
openssl-1.0.2h  94% |#############################  | ETA:  0:00:00  26.56 MB/s
openssl-1.0.2h  96% |#############################  | ETA:  0:00:00  26.57 MB/s
openssl-1.0.2h  97% |############################## | ETA:  0:00:00  26.72 MB/s
openssl-1.0.2h  99% |############################## | ETA:  0:00:00  26.87 MB/s
openssl-1.0.2h 100% |###############################| Time: 0:00:00  26.94 MB/s
sqlite-3.13.0-   0% |                              | ETA:  --:--:--   0.00  B/s
Command time: 3s Return: 1
```

https://readthedocs.org/projects/ga4gh-schemas/builds/5051360/

https://github.com/conda/conda/issues/4693

**Comment by david4096** [comment]
After many kinds words, RTD has issued the fix for this. Please confirm by rerunning the latest docs build and closing this issue.

**Comment by dcolligan** [comment]
Schemas build is passing https://readthedocs.org/projects/ga4gh-schemas/builds/5116967/

Closing...
